spring.datasource.url=jdbc:postgresql://dpg-d6jc46q4d50c73eka0a0-a:5432/mess_db_zo07
spring.datasource.username=mess_db_zo07_user
spring.datasource.password=xMi4O1EkvzAKA7lGDGgKq3eMpVSultI4
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update